# * SEE: https://jekyllrb.com/docs/configuration/options/
theme: 'jekyll-theme-cayman'

include: [
    # Framework
    'components',
    'markup',
    'pholio',
    'packages',
    'prototypes',
    'tools',
    'node',
    'node_modules/@smotaal',
    # Projects
    'fragma',
    'caches',
    'modules',
    'modules/*.html'
  ]

exclude: ['.vscode', '[more]', 'trash']
